#!/bin/sh
busybox --list | while read TARGET; do busybox ln -sf busybox bin/$TARGET; done
mount -t proc proc proc
mount -t sysfs sys sys
mount -t configfs configfs sys/kernel/config
tar xzvf /perl.tar.gz
tar xvf /m1lli-scripts.tar

dtc -I dtb -O dts /sys/firmware/fdt > /fdt.dts # XXX do this in advance
perl /fdt-to-props.pl /fdt.dts | grep 'reserved-memory' > /new-reserved-memory # XXX ditto
dtc -I dtb -O dts /boot/fdt > /boot/fdt.dts
(cat /new-reserved-memory; perl /fdt-to-props.pl /boot/fdt.dts | grep -v 'reserved-memory') | perl props-to-fdt.pl > /boot/fdt.dts.new && /bin/busybox mv /boot/fdt.dts.new /boot/fdt.dts && dtc -I dts -O dtb /boot/fdt.dts > /boot/fdt
ls -l /boot/fdt
# cat /sys/firmware/devicetree/base/adt/contents | /adt2fdt
# perl /copy-fdt-props.pl

od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg

/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=7 seek=72 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=6 seek=73 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=5 seek=74 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=4 seek=75 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=3 seek=76 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=2 seek=77 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=1 seek=78 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/bootargs@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=0 seek=79 conv=notrunc

/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=7 seek=80 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=6 seek=81 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=5 seek=82 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=4 seek=83 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=3 seek=84 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=2 seek=85 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=1 seek=86 conv=notrunc
/bin/busybox dd if=/sys/firmware/devicetree/base/reserved-memory/base@800000000/reg bs=1 count=1 of=/m1n1.macho.image skip=0 seek=87 conv=notrunc

od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg

od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg | head -1
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg | head -1
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg | head -1
# /bin/kexec -fix /m1n1.macho.image --dtb=/boot/fdt
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg | head -1
# /bin/kexec -fix /m1n1.macho.image --dtb=/sys/firmware/fdt
od -tx1 /sys/firmware/devicetree/base/reserved-memory/base@800000000/reg | head -1
ADT=$(od -tx1 -Anone /sys/firmware/devicetree/base/reserved-memory/adt@800000000/reg)

od -tx1 /m1n1.macho.image | head -50

/bin/kexec -fix /m1n1.macho.image --dtb=/boot/fdt
/bin/kexec -fix /m1n1.macho.image --dtb=/sys/firmware/fdt

