#!/bin/sh
busybox --list | while read TARGET; do busybox ln -sf busybox bin/$TARGET; done
mount -t proc proc proc
mount -t sysfs sys sys
mount -t configfs configfs sys/kernel/config
tar xzvf /perl.tar.gz
tar xvf /m1lli-scripts.tar

touch /mmio-map
touch /mmio-log
# tail -f /mmio-log &
touch /pt-log
# tail -f /pt-log &

(while true; do mmio; sleep 1; done) &
mmio init &
COUNT=1
#(seq 1 10000000 | while read i; do
#     echo $(wc -l mmio-map) $i
#     (wait4pt $(cat addr) > addr2 && mv addr2 addr)
#     pt unmap-pa 0x23d2b0000 0x23d2b4000
#     pt unmap-pa 0x200000000 0x23b000000
#     pt unmap-pa 0x23b200000 0x300000000
#     # pt unmap-pa 0xbdf438000 0xbe03d8000
#     pt unmap-pa 0x23e400000
#     pt unmap-pa 0x23e050000
#     wait4pt clear $(cat addr) || echo "not active"
# done) &
# (while sleep 1m; do cat mmio-map; done) &
# (sleep 5m; while sleep 3; do
#      pt unmap-pa 0x23d2b0000 0x23d2b4000
#      pt unmap-pa 0x200000000 0x23b000000
#      pt unmap-pa 0x23b200000 0x300000000
#      # pt unmap-pa 0xbdf438000 0xbe03d8000
#      pt unmap-pa 0x23e400000
#      pt unmap-pa 0x23e050000
#  done) &
# (while true; do memtool mw 0x210030fb0 0xc5acce55; memtool md 0x210040090+8; sleep 5; done) &
# echo "init2 done"
(sleep 1m; while true; do /bin/scanmem; sleep 1; done) &

sleep 1

# (while true; do
#      memtool md 0x23d2b000c+4 | grep '00000003' && memtool mw 0x23d2b000c 3
#      memtool mw 0x23d2b0048 0
#      sleep .1
#  done) &


while true; do
    for i in $(seq 1 80); do
	sleep 1
	continue
	# memtool mw 0x23d2b0010 0 0xffffffff 0 0
	# echo heartbeat > /sys/class/leds/kbd_backlight/trigger
	memtool mw 0x235044018 0 128
	memtool mw 0x235044000 0x4239
	# # # memtool md 0x23b102000
	memtool mw 0x23b7001d8 0xf
	memtool mw 0x23b7001e0 0xf
	# #	cat /proc/interrupts
	# #	cat /proc/iomem
	# memtool mw 0x23d2b0010 0 0xffffffff 0 0
	sleep 1
	memtool mw 0x235044018 128 0
	memtool mw 0x235044000 0x4239
	# # # memtool md 0x23b102000
	memtool mw 0x23b7001d8 0xf
	memtool mw 0x23b7001e0 0xf
	# memtool mw 0x23d2b0010 1000 0 0 4
	#cat /proc/interrupts
	#cat /proc/iomem
	# [ -e /start-wait4mmio ] && (rm /start-wait4mmio; (while true; do wait4mmio >> /log 2> /log2; done) &)
	#[ -e /start-wait4mmio ] && (rm /start-wait4mmio; (while true; do wait4mmio; done) & pt unmap-pa 0x23b100000)
	# pt remap-pa 0x23b100000
    done
done
