#!/bin/sh
mkdir /mnt
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount /dev/nvme0n1p4 /mnt
cp modules/*.ko /mnt
sync
while sleep 1; do cat /sys/class/power_supply/smc_battery/energy_now; done &
/bin/sh
exec /bin/busybox switch_root /mnt /sbin/init
