#!/bin/sh
mkdir /mnt
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sys /sys
/bin/busybox mount -t devtmpfs dev /dev
/bin/busybox mount /dev/nvme0n1p4 /mnt
cp modules/*.ko /mnt
/bin/busybox sync
while sleep 1; do cat /sys/class/power_supply/Apple*/energy_now; done &
/bin/sh
exec /bin/busybox switch_root /mnt /sbin/init
